### ISSUE TITLE
setup example structure

### ISSUE THREAD

**Issue by FFrese90** [FFrese90/example_workflow_repo#1]
### Issue Details
- **Title:** setup example structure
- **Description:** Create a folder structure with a basic GitHub action workflow with hello world example
- **State:** Open
- **Created Time:** 6 days ago
- **Updated Time:** 6 days ago
- **Author:** [FFrese90](https://github.com/FFrese90)
- **URL:** [Issue #1](https://github.com/FFrese90/example_workflow_repo/issues/1)

### Suggested Next Steps
1. **Plan the Folder Structure:**
   - Determine the directories needed, such as `.github/workflows` for the GitHub Action workflow.
   - Consider any other directories or files you might need for the "hello world" example.

2. **Create the Folder Structure:**
   - Create the necessary directories and files in your local repository.
   - Example:
     ```plaintext
     .github/
       └── workflows/
            └── hello-world.yml
     ```

3. **Define the GitHub Action Workflow:**
   - Create a basic workflow file. For example, create `hello-world.yml` inside `.github/workflows` with the following content:
     ```yaml
     name: Hello World

     on: [push]

     jobs:
       build:
         runs-on: ubuntu-latest
         steps:
         - uses: actions/checkout@v2
         - name: Run a one-line script
           run: echo "Hello, world!"
     ```

4. **Commit and Push Changes:**
   - Commit the changes to your local repository.
     ```sh
     git add .
     git commit -m "Setup example structure with hello world GitHub Action"
     ```
   - Push the changes to your remote repository.
     ```sh
     git push origin <branch-name>
     ```

5. **Verify the Workflow Execution:**
   - Once the changes are pushed, GitHub Actions should trigger the workflow.
   - Verify that the "Hello World" action runs successfully by checking the Actions tab in your repository.

If you have any specific questions or need further assistance with any of the steps, feel free to ask!
